### ISSUE TITLE
Michael got sick

### ISSUE THREAD

**Issue by outvoider** [once-ler/durian#5]
Hi Henry,

I got sick and will not be coming today and perhaps tomorrow. Please, tell Joe about this, because I am not sure if he got my email or voice message.

Michael

**Comment by htaox** [comment]
@outvoider uh um, I've never seen anyone use GitHub issues like this before.

No problem, I'll let Joe know and hope you feel better!

**Comment by rogerchengnjit** [comment]
Get well soon!
